a_core/urls.py
from django.contrib import admin
from django.urls import path, include
from a_posts.views import *
from a_users.views import *
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('offical/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('' , home_view, name="home"),
    path('category/<tag_slug>/' , home_view, name="category"),
    
    path('post/create/' , post_create_view, name="post-create"),
    path('post/delete/<pk>/' , post_delete_view, name="post-delete"),
    path('post/edit/<pk>/' , post_edit_view, name="post-edit"),
    path('post/<pk>/' , post_page_view, name="post"),
    path('post/like/<pk>/' , like_post , name="like-post"),
    
    path('profile/' , profile_view, name="profile"),
    path('search_users/' , search_share_users_view, name="share-searchusers"),
    path('sharepost/' , share_post , name="share-post"),    
    
    
    path('inbox/', include('a_inbox.urls')),
    
    
    path('<username>/' , profile_view, name="userprofile"),
    path('profile/edit/' , profile_edit_view, name="profile-edit"),
    path('profile/delete/' , profile_delete_view, name="profile-delete"),
    path('profile/onboarding/' , profile_edit_view, name="profile-onboarding"),
    
    path('commentsent/<pk>/' , comment_sent, name='comment-sent'),
    path('comment/delete/<pk>' , comment_delete_view, name='comment-delete'),
    path('comment/like/<pk>/' , like_comment , name="like-comment"),

    path('reply-sent/<pk>/' , reply_sent, name='reply-sent'),
    path('reply/delete/<pk>' , reply_delete_view, name='reply-delete'),
    path('reply/like/<pk>/' , like_reply , name="like-reply"),  
        
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

a_inbox/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('' , inbox_view, name="inbox"),
    path('c/<conversation_id>/' , inbox_view, name="inbox"),
    path('search_users/' , search_users_view, name="inbox-searchusers"),
    path('new_message/<recipient_id>/' , new_message, name="inbox-newmessage"),
    path('new_reply/<conversation_id>/' , new_reply, name="inbox-newreply"),
    path('notify_newmessage/<conversation_id>/' , notify_newmessage, name="notify-newmessage"),
    path('notify_inbox/' , notify_inbox, name="notify-inbox"),
]

a_inbox/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.utils import timezone
from django.utils.timesince import timesince
from a_posts.models import Post
# Create your models here.

''' the relationship specified by sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sent_messages") indicates a "many-to-one" relationship between the InboxMessage table and the User table.

In a many-to-one relationship:

"Many" refers to the fact that one user can have multiple inbox messages (or sent messages in this case).
"One" refers to the fact that each inbox message is associated with exactly one user (the sender).
So, to clarify:

The "many" side is represented by the InboxMessage model, as it can have many instances associated with a single user.
The "one" side is represented by the User model, as each inbox message is sent by exactly one user.
In simpler terms, each inbox message belongs to one user (the sender), but one user can have many inbox messages. '''

class InboxMessage(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sent_messages")
    conversation = models.ForeignKey("Conversation", on_delete=models.CASCADE, related_name="messages")
    body = models.TextField()
    share_post = models.ForeignKey(Post, on_delete=models.SET_NULL, null=True, blank=True, related_name="share_in_messages")
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']
        
    def __str__(self):
        time_since = timesince(self.created, timezone.now())
        return f'{self.sender.username} : {time_since} ago '
    
class Conversation(models.Model):
    id = models.CharField(max_length=150, default=uuid.uuid4, editable=False, primary_key=True, unique=True)
    participants = models.ManyToManyField(User, related_name="conversations")
    lastmessage_created = models.DateField(default=timezone.now())
    is_seen = models.BooleanField(default=False)
    
    class Meta:
        ordering = ['-lastmessage_created']
        
    def __str__(self):
        user_names = ", ".join( user.username for user in self.participants.all())
        return f"[ {user_names} ]"

a_inbox/forms.py
from django.forms import ModelForm
from django import forms
from .models import InboxMessage


class InboxNewMessageForm(forms.ModelForm):
    
    class Meta:
        model = InboxMessage
        fields = (['body'])
        
        labels = {
            'body' : '',
        }
        widgets = {
            'body' : forms.Textarea(attrs={'rows' : 4, 'placeholder'  : 'Add message ... '})
        }

a_inbox/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from a_users.models import Profile
from django.http import HttpResponse, Http404
from django.db.models import Q
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required
def inbox_view(request, conversation_id=None):
    my_conversation = Conversation.objects.filter(participants = request.user)
    if conversation_id:
        conversation = get_object_or_404(my_conversation, id = conversation_id)
        latest_message = conversation.messages.first()
        if conversation.is_seen == False and latest_message.sender != request.user:
            conversation.is_seen = True
            conversation.save()
    else:
        conversation = None   
    context = {
        'conversation' : conversation,
        'my_conversation' : my_conversation
    }
    return render(request, 'a_inbox/inbox.html', context)

    
def search_users():
    def inner_func(func):
        def wrapper(request, *args, **kwargs):
            letters = request.GET.get('search_user')
            if request.htmx:
                if len(letters) > 0:
                    
                    profiles = Profile.objects.filter(realname__icontains=letters).exclude(realname = request.user.profile.realname)

                    users_id = profiles.values_list('user', flat=True)
                    
                    users = User.objects.filter(
                        Q(username__startswith=letters) | Q(id__in = users_id)
                    ).exclude(username = request.user.username)
                    
                    return func(request, users)
                else:
                    return HttpResponse('')
            else:
                raise Http404()
        return wrapper
    return inner_func
            
@search_users()
def search_users_view(request, users):
    return render(request, 'a_inbox/list_searchusers.html', {'users' : users}) 
                     

@login_required
def new_message(request, recipient_id):
    recipient = get_object_or_404(User, id = recipient_id)
    new_message_form = InboxNewMessageForm()
    
    if request.method == 'POST':
        
        form = InboxNewMessageForm(request.POST)
        print(form , '      form')
        if form.is_valid():
            
            message = form.save(commit=False)
            message.sender = request.user

            my_conversations = request.user.conversations.all()
            
            for c in my_conversations:
                
                if recipient in c.participants.all():
                    
                    message.conversation = c
                    message.save()
                    
                    c.lastmessage_created = timezone.now()
                    c.is_seen = False
                    c.save()
                    
                    return redirect('inbox', c.id)

            new_conversation = Conversation.objects.create()
            new_conversation.lastmessage_created = timezone.now()
            new_conversation.participants.add(request.user, recipient)
            new_conversation.save()
            
            message.conversation = new_conversation
            message.save()
            
            return redirect('inbox', new_conversation.id)              
    
    context = {'new_message_form' : new_message_form, 'recipient' : recipient}
    
    return render(request, 'a_inbox/form_newmessage.html', context)
     
@login_required    
def new_reply(request, conversation_id):
    
    new_reply_form = InboxNewMessageForm()
    my_conversation = request.user.conversations.all()

    conversation = get_object_or_404(my_conversation, id = conversation_id )
    
    if request.method == 'POST':
        form = InboxNewMessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = request.user
            message.conversation = conversation
            message.save()
            
            conversation.lastmessage_created = timezone.now()
            conversation.is_seen = False
            conversation.save()
            
            return redirect('inbox', conversation.id)

    context = { 'new_reply_form' : new_reply_form, 'conversation' : conversation}
    return render(request, 'a_inbox/form_newreply.html', context)
    
    
@login_required
def notify_newmessage(request, conversation_id):
    conversation = get_object_or_404(Conversation, id = conversation_id)
    latest_message = conversation.messages.first()
    if conversation.is_seen == False and latest_message.sender != request.user:
        return render(request, 'a_inbox/notify_icon.html')
    else:
        return HttpResponse('')
    
def notify_inbox(request):
    my_conversation = Conversation.objects.filter(participants=request.user, is_seen=False)
    for c in my_conversation:
        latest_message = c.messages.first()
        if latest_message.sender != request.user:
            return render(request, 'a_inbox/notify_icon.html')
    else:
        return HttpResponse('') 
    

a_inbox/templates/a_inbox/chat_bubble.html
    {% if message.sender == request.user %}
    <!-- Sent -->
    <li class="clear-both py-4">
        <div class="flex items-end gap-3">
            <div>
                <img src="{{ message.sender.profile.avatar }}" alt="" class="rounded-full h-9 w-9">
            </div>

            <div>
                <div class="flex gap-2 mb-2">
                    <div class="relative px-5 py-3 text-white rounded-lg ltr:rounded-bl-none rtl:rounded-br-none group-data-[theme-color=violet]:bg-violet-500 group-data-[theme-color=green]:bg-green-500 group-data-[theme-color=red]:bg-red-500">
                        <p class="mb-0">
                            {{message.body}}
                        </p>
                        <p class="mt-1 mb-0 text-xs text-right text-white/50"><i class="align-middle ri-time-line"></i> <span class="align-middle">{{ message.created|timesince }}</span></p>
                        <div class="before:content-[''] before:absolute before:border-[5px] before:border-transparent group-data-[theme-color=violet]:ltr:before:border-l-violet-500 group-data-[theme-color=violet]:ltr:before:border-t-violet-500 group-data-[theme-color=green]:ltr:before:border-l-green-500 group-data-[theme-color=green]:ltr:before:border-t-green-500 group-data-[theme-color=red]:ltr:before:border-l-red-500 group-data-[theme-color=red]:ltr:before:border-t-red-500 group-data-[theme-color=violet]:rtl:before:border-r-violet-500 group-data-[theme-color=violet]:rtl:before:border-t-violet-500 group-data-[theme-color=green]:rtl:before:border-r-green-500 group-data-[theme-color=green]:rtl:before:border-t-green-500 group-data-[theme-color=red]:rtl:before:border-r-red-500 group-data-[theme-color=red]:rtl:before:border-t-red-500 ltr:before:left-0 rtl:before:right-0 before:-bottom-2"></div>
                    </div>
                    <div class="relative self-start dropdown">
                        <a class="p-0 text-gray-400 border-0 btn dropdown-toggle dark:text-gray-100" href="#" role="button" data-bs-toggle="dropdown" id="dropdownMenuButton12">
                            <i class="ri-more-2-fill"></i>
                        </a>
                        <div class="absolute z-50 hidden w-40 py-2 my-6 text-left list-none bg-white border-none rounded shadow-lg ltr:left-auto ltr:right-0 xl:ltr:left-0 xl:ltr:right-auto rtl:left-0 rtl:right-auto xl:rtl:right-0 xl:rtl:left-auto dropdown-menu bg-clip-padding dark:bg-zinc-700 dark:border-gray-600/50" aria-labelledby="dropdownMenuButton12">
                            <a class="block w-full px-4 py-2 text-sm font-normal text-gray-700 bg-transparent dropdown-item whitespace-nowrap hover:bg-gray-100/50 dark:text-gray-100 dark:hover:bg-zinc-600 ltr:text-left rtl:text-right" href="#">Copy <i class="text-gray-500 rtl:float-left ltr:float-right dark:text-gray-200 ri-file-copy-line"></i></a>
                            <a class="block w-full px-4 py-2 text-sm font-normal text-gray-700 bg-transparent dropdown-item whitespace-nowrap hover:bg-gray-100/50 dark:text-gray-100 dark:hover:bg-zinc-600 ltr:text-left rtl:text-right" href="#">Save <i class="text-gray-500 rtl:float-left ltr:float-right dark:text-gray-200 ri-save-line"></i></a>
                            <a class="block w-full px-4 py-2 text-sm font-normal text-gray-700 bg-transparent dropdown-item whitespace-nowrap hover:bg-gray-100/50 dark:text-gray-100 dark:hover:bg-zinc-600 ltr:text-left rtl:text-right" href="#">Forward <i class="text-gray-500 rtl:float-left ltr:float-right dark:text-gray-200 ri-chat-forward-line"></i></a>
                            <a class="block w-full px-4 py-2 text-sm font-normal text-gray-700 bg-transparent dropdown-item whitespace-nowrap hover:bg-gray-100/50 dark:text-gray-100 dark:hover:bg-zinc-600 ltr:text-left rtl:text-right" href="#">Delete <i class="text-gray-500 rtl:float-left ltr:float-right dark:text-gray-200 ri-delete-bin-line"></i></a>
                        </div>
                    </div>
                </div>
                <div class="font-medium text-gray-700 text-14 dark:text-gray-300">{{ message.sender.username }}</div>
            </div>
        </div>
    </li>
    {% else %}
    <!-- Recieved -->
    <li class="clear-both py-4">
        <div class="relative inline-flex items-end mb-6 text-right ltr:rtl:float-left ltr:float-right rtl:float-left">
            <div class="order-3 mr-0 ltr:ml-4 rtl:mr-4">
                <img src="{{ message.sender.profile.avatar }}" alt="" class="rounded-full h-9 w-9">
            </div>

            <div>
                <div class="flex gap-2 mb-2 ltr:justify-end rtl:justify-start">
                    <div class="relative order-2 px-5 py-3 text-gray-700 rounded-lg ltr:rounded-br-none rtl:rounded-bl-none bg-gray-50 dark:bg-zinc-700 dark:text-gray-50">
                        <p class="mb-0">
                            {{ message.body }}
                        </p>
                        <p class="mt-1 mb-0 text-xs text-left text-gray-500 dark:text-gray-300"><i class="align-middle ri-time-line"></i> <span class="align-middle">{{ message.created|timesince }}</span></p>
                        <div class="before:content-[''] before:absolute before:border-[5px] before:border-transparent ltr:before:border-r-gray-50 ltr:before:border-t-gray-50 rtl:before:border-l-gray-50 rtl:before:border-t-gray-50 ltr:before:right-0 rtl:before:left-0 before:-bottom-2 ltr:dark:before:border-t-zinc-700 ltr:dark:before:border-r-zinc-700 rtl:dark:before:border-t-zinc-700 rtl:dark:before:border-l-zinc-700"></div>
                    </div>

                    <div class="relative self-start order-1 dropstart">
                        <a class="p-0 text-gray-400 border-0 btn dropdown-toggle dark:text-gray-100" href="#" role="button" data-bs-toggle="dropdown" id="dropdownMenuButton13">
                            <i class="ri-more-2-fill"></i>
                        </a>
                        <div class="absolute z-50 hidden py-2 my-6 text-left list-none bg-white border-none rounded shadow-lg ltr:right-auto ltr:left-0 xl:ltr:right-0 xl:ltr:left-auto rtl:right-0 rtl:left-auto xl:rtl:left-0 xl:rtl:right-auto dropdown-menu w-36 bg-clip-padding dark:bg-zinc-700" aria-labelledby="dropdownMenuButton13">
                            <a class="block w-full px-4 py-2 text-sm font-normal text-gray-700 bg-transparent dropdown-item whitespace-nowrap hover:bg-gray-100/50 dark:text-gray-100 dark:hover:bg-zinc-600 ltr:text-left rtl:text-right" href="#">Copy <i class="text-gray-500 rtl:float-left ltr:float-right dark:text-gray-200 ri-file-copy-line"></i></a>
                            <a class="block w-full px-4 py-2 text-sm font-normal text-gray-700 bg-transparent dropdown-item whitespace-nowrap hover:bg-gray-100/50 dark:text-gray-100 dark:hover:bg-zinc-600 ltr:text-left rtl:text-right" href="#">Save <i class="text-gray-500 rtl:float-left ltr:float-right dark:text-gray-200 ri-save-line"></i></a>
                            <a class="block w-full px-4 py-2 text-sm font-normal text-gray-700 bg-transparent dropdown-item whitespace-nowrap hover:bg-gray-100/50 dark:text-gray-100 dark:hover:bg-zinc-600 ltr:text-left rtl:text-right" href="#">Forward <i class="text-gray-500 rtl:float-left ltr:float-right dark:text-gray-200 ri-chat-forward-line"></i></a>
                            <a class="block w-full px-4 py-2 text-sm font-normal text-gray-700 bg-transparent dropdown-item whitespace-nowrap hover:bg-gray-100/50 dark:text-gray-100 dark:hover:bg-zinc-600 ltr:text-left rtl:text-right" href="#">Delete <i class="text-gray-500 rtl:float-left ltr:float-right dark:text-gray-200 ri-delete-bin-line"></i></a>
                        </div>
                    </div>
                </div>

                <div class="font-medium text-gray-700 rtl:text-left text-14 dark:text-gray-300">Patricia Smith</div>
            </div>
        </div>
    </li>
    {% endif %}

a_inbox/templates/a_inbox/conversation.html
{% load static %}
<div id='conversation'
    class="col-span-4 sm:col-span-3 opacity-0 flex flex-col bg-white rounded-r-2xl pt-10 relative overflow-y-auto"
    _="on load wait for 5ms then remove .opacity-0">

    {% if conversation %}
      
    <div class="text-center flex flex-col items-center">
        {% for participant in conversation.participants.all %}
          {% if participant != request.user %}
            
        <a href="{% url 'userprofile' participant.username %}" class="flex items-center">
            <img class="w-24 h-24 rounded-full object-cover mb-4"
                src="{{ participant.profile.avatar }}" />
        </a>
        <div class="text-center max-w-md">
            <div class="flex items-center">
            <h1 class="text-lg">{{ participant.profile.name }}</h1>
                {% if participant.is_superuser %}    
                <img class="w-4 h-4 ml-1 mb-4" src="{% static 'images/verified.png' %}"/>
                {% endif %}
            </div>
            <div class="text-gray-400 mb-2 -mt-5 text-sm">@{{ participant.username }}</div>
        </div>
        {% endif %}
        {% endfor %}
    </div>

    <ul id='inbox_messages' class="flex flex-col justify-end grow gap-6 p-4 sm:p-10 pb-0 sm:pb-0 ">
        {% for message in conversation.messages.all reversed %}          
        <li>
            <div class="flex flex-col md:flex-row gap-1 md:gap-6">
                <a class="contents" href="{% url 'userprofile' message.sender.username %}">
                    <img class="w-14 h-14 object-cover rounded-full" src="{{ message.sender.profile.avatar }}">
                </a>
                <div class="bg-white p-4 w-full rounded-xl border-2 border-gray-200">
                    <div class="flex flex-col md:flex-row justify-between text-xs pb-3 text-zinc-500">
                        <div>
                            <span class="font-bold text-base text-black mr-1">{{message.sender.profile.name}}</span>{{message.sender.username}}
                        </div>
                        <div>{{ message.created }} ({{ message.created|timesince }})</div>
                    </div>
                    {% if message.body %}                      
                    <div>
                        <p class="whitespace-pre-wrap">{{ message.body }}</p>
                    </div>
                    {% endif %}
                    {% if message.share_post %}
                    <div class="shared-post">
                        <a href="{% url 'post' message.share_post.id %}">
                            <img src="{{ message.share_post.image }}" class="w-30" alt="Post Image">
                        </a>
                    </div>
                    {% endif %}

                </div>
            </div>
        </li>
        
        {% endfor %}

    </ul>

    <div class="sticky bottom-0 z-1 px-4 sm:px-10 pt-6 pb-10 flex bg-white">
        <a class="flex cursor-pointer items-center gap-2 bg-gray-800 hover:bg-indigo-600 text-white rounded-full px-6 pr-8 py-3"
            hx-get="{% url 'inbox-newreply' conversation.id %}" 
            hx-target="this"
            hx-swap="outerHTML scroll:#conversation:bottom ">
            <img class="h-6" src="https://img.icons8.com/material/96/ffffff/reply-arrow--v1.png">
            <div class="text-white rounded-full">Reply</div>
        </a>
    </div>

    {% else %}
    <div class="h-full flex items-center justify-center text-gray-500 -mt-6 text-center p-10">Select a conversaiton or create a new message</div>
    {% endif %}


</div>

a_inbox/templates/a_inbox/form_newmessage.html
<div class="flex gap-2 items-center mb-5">
    <span class="font-bold">To:</span>
    <div class="flex items-center gap-1">
        <img class="w-10 h-10 object-cover rounded-full mr-1" src="{{recipient.profile.avatar}}">
        <div class="font-bold">
            {{ recipient.profile.name }}
            <span class="text-xs font-normal text-zinc-500">@{{recipient.username}}</span>

            <!-- <span class="text-xs font-bold text-red-500 pl-2">User not verified!</span> -->

        </div>
    </div>
</div>


<div class="mb-5">
    <form method="POST" action="{% url 'inbox-newmessage' recipient.id %}">
        {% csrf_token %}
        {{ new_message_form }}
        <button type="submit" class="mt-1">Submit Message</button>
        <a @click="modal_open = false" href="{{ request.META.HTTP_REFERER }}"
            class="button secondaryAction ml-1 cursor-pointer" _="on click reset() the closest <form/>">Cancel</a>
    </form>
</div>

a_inbox/templates/a_inbox/form_newreply.html
<div class="flex flex-col md:flex-row gap-1 md:gap-6 w-full">
    <img class="w-14 h-14 object-cover rounded-full" src="{{ user.profile.avatar }}">
    <form method="POST" action="{% url 'inbox-newreply' conversation.id %}" class="w-full">
        {% csrf_token %}

        {{ new_reply_form }}

            <!-- <wordtune-suggestions-container-block
                style="position: absolute; overflow: hidden; pointer-events: none; width: 527px; height: 128px; top: 24px; left: 120px; padding: 16px 19.2px; margin: 0px 0px 16px;"><wordtune-suggestions-container
                    style="width: 527px; display: block; height: 128px;"></wordtune-suggestions-container></wordtune-suggestions-container-block><wordtune-cards-container
                id="wordtune-cards-container-id" style="z-index: 999;"></wordtune-cards-container> -->
        
        <div class="flex justify-between">
            <button type="submit" class="mt-1">Send Message</button>
            <a class="button secondaryAction ml-1"
                href="{{ request.META.HTTP_REFERER }}">Cancel</a>
        </div>
    </form>
</div>

a_inbox/templates/a_inbox/form_searchuser.html
<h3 class="text-xl font-bold mb-4" id="modal-title">
    New Message
</h3>
<div id="new-message">
    <div class="flex gap-2 items-center">
        <span class="font-bold">To:</span>
        <input class="p-3 w-screen lg:full" placeholder="Search user ..." type="text" name="search_user"
        hx-get="{% url 'inbox-searchusers' %}"
        hx-trigger="keyup changed"
        hx-target="#search-results"
        hx-swap="innerHTML" >
    </div>
    <div id="search-results" class="block h-60 overflow-y-auto">
    
    </div>
</div>

a_inbox/templates/a_inbox/inbox.html
{% extends "layouts/d.html" %}
{% load static %}

{% block content %}

<inbox
    class="grid grid-cols-5 sm:grid-cols-4 h-[calc(100vh-8rem)] md:h-[calc(100vh-12rem)] shadow-2xl rounded-2xl mx-1 lg:mx-10 xl:mx-48">
    <div x-data="{ modal_open: false }" class="col-span-1 bg-slate-10 rounded-l-2xl p-2 overflow-y-auto">

        <div class="p-0 sm:p-4 mb-3 sticky top-0 z-10">
            <a @click="modal_open = true"
                class="flex cursor-pointer items-center justify-center h-14 sm:h-16 gap-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-full">
                <img class="h-6 m-auto lg:m-0"
                    src="https://img.icons8.com/external-anggara-glyph-anggara-putra/32/ffffff/external-edit-user-interface-anggara-glyph-anggara-putra.png">
                <div class="hidden lg:block text-white rounded-full font-bold">New Message</div>
            </a>
        </div>

        <div x-show="modal_open" x-cloak class="relative z-10" aria-labelledby="modal-title" role="dialog"
            aria-modal="true">
            <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>
            <div class="fixed inset-0 z-10 w-screen overflow-y-auto">
                <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
                    <div
                        class="relative transform overflow-hidden rounded-2xl bg-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">
                        <div @click.away="modal_open = false" class="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
                            {% include "a_inbox/form_searchuser.html" %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% include "a_inbox/my_conversation.html" %}
    </div>
    {% include "a_inbox/conversation.html" %}
</inbox>


<script>
    function scrollToBottom() {
        const container = document.getElementById('conversation');
        container.scrollTop = container.scrollHeight;
    }

    window.onload = function () {
        scrollToBottom();
    };
</script>



{% endblock content %}

a_inbox/templates/a_inbox/inbox_post.html
 <li>
    <!-- Instagram Share Post Card -->
  <div class="w-30 p-2 bg-white rounded-xl shadow-lg">
    <!-- Header -->
    <div class="flex items-center p-2 bg-gray-200 rounded-t-lg">
      <img src="{{ message.sender.profile.avatar }}" alt="Profile Avatar" class="w-10 h-10 rounded-full">
      <span class="ml-3 font-semibold">{{ message.sender.username }}</span>
    </div>

    <!-- Post Image -->
    <div class="w-full">
      <img src="{{ message.share_post.image }}" alt="Post Image" class="w-full">
    </div>

    <!-- Caption -->
    <div class="p-2 bg-gray-200 rounded-b-lg">
      <p class="text-sm">{{ message.share_post.body }}</p>
    </div>
  </div>
 </li>

a_inbox/templates/a_inbox/notify_icon.html
<div class="rounded-full bg-blue-500 p-1.5"></div>

a_inbox/templates/a_inbox/reply.html
<div class="sticky bottom-0 z-1 px-4 sm:px-10 pt-6 pb-10 flex bg-white">
    <div class="flex flex-col md:flex-row gap-1 md:gap-6 w-full">
        <img class="w-14 h-14 object-cover rounded-full" src="/static/images/avatar_default.svg">
        <form method="POST" action="/inbox/new_reply/ccc6c1c3-61a5-4c28-85e1-00c04efd192e/" class="w-full">
            <input type="hidden" name="csrfmiddlewaretoken"
                value="3go8kNdw51oTC81mkFua8Yb8ZqUYnqUBsD0o8GsMCGyUrQYRaSsEit9TTBj1XBQV">
            <div>
                <textarea name="body" cols="40" rows="4" placeholder="Add message ..." maxlength="2000" required=""
                    id="id_body"></textarea>



                <wordtune-suggestions-container-block
                    style="position: absolute; overflow: hidden; pointer-events: none; width: 527px; height: 128px; top: 24px; left: 120px; padding: 16px 19.2px; margin: 0px 0px 16px;"><wordtune-suggestions-container
                        style="width: 527px; display: block; height: 128px;"></wordtune-suggestions-container></wordtune-suggestions-container-block><wordtune-cards-container
                    id="wordtune-cards-container-id" style="z-index: 999;"></wordtune-cards-container>
            </div>
            <div class="flex justify-between">
                <button type="submit" class="mt-1">Send Message</button>
                <a class="button secondaryAction ml-1"
                    href="https://awesomepixx.com/inbox/c/ccc6c1c3-61a5-4c28-85e1-00c04efd192e/">Cancel</a>
            </div>
        </form>
    </div>
</div>